version: '3'
services:
  rss2tg_dev:
    container_name: rss2tg_dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - type: bind
        source: .
        target: /app/src
    environment:
      - TZ=Asia/Shanghai
      - TELEGRAM_API_URL=http://fyapi.deno.dev/telegram  # 自定义Telegram API代理地址 (重要：国内服务器必须配置)
    restart: "no"
    privileged: true
    ports:
      - "2345:2345"
    tty: true
    stdin_open: true