version: '3'
services:
  rss2tg:
    container_name: rss2tg
    image: drfyup/rss2tg:latest
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - ./data:/app/data
    environment:
      - TELEGRAM_BOT_TOKEN=  # 你的Telegram Bot Token
      - TELEGRAM_USERS=      # 接收消息的用户ID，多个用逗号分隔
      - TELEGRAM_CHANNELS=   # 接收消息的频道，多个用逗号分隔
      # 设置以下代理地址之一（根据实际可用情况选择）
      # 方式1：使用 fyapi.deno.dev 代理（默认推荐）
      - TELEGRAM_API_URL=http://fyapi.deno.dev/telegram
      # 方式2：使用查询参数格式的代理（如果方式1不工作）
      #- TELEGRAM_API_URL=http://fyapi.deno.dev/telegram?api=
      # 方式3：使用您自己的反向代理
      #- TELEGRAM_API_URL=http://your-own-proxy.com/telegram
      - TZ=Asia/Shanghai     # 时区设置
    restart: unless-stopped
